### ISSUE TITLE
Splash Screen causes app to crash

### ISSUE THREAD

**Issue by keerthanss** [keerthanss/Location-Alarm-App-Project#1]
I'm not yet sure if this is always true, and haven't been able to find out the reason. Basically, the Splash Screen shows no problem. Stays for three seconds, and then loads Main Activity. Immediately after loading though, the app crashes no matter what.
Must fix soon, only if we do decide to implement a splash screen

**Comment by Srinivas-R** [comment]
Have you updated the manifest for all objects? A null pointer usually causes crash after activity switch.

**Comment by keerthanss** [comment]
Yeah, I did

**Comment by keerthanss** [comment]
It apparently wasn't the splash screen fault! My location wasn't working properly. Set it to high accuracy and the app works fine now. The issue is resolved :P

**Comment by keerthanss** [comment]
Oh and guess who helped me figure it out! Derek Banas :P the youtube guy. he's awesome, he always replies to the comments

**Comment by Srinivas-R** [comment]
Huh.. pretty cool guy then :P
Good that it's fixed
