### ISSUE TITLE
App crashes upon changing tabs

### ISSUE THREAD

**Issue by keerthanss** [keerthanss/Location-Alarm-App-Project#3]
Weird scenario. First tab ("Maps") to second ("Alarms") and back- no problem.Go to third tab ("Settings") from either of the first two - no problem. Switch from settings to alarm/map - app crashes.

Log report - 
FATAL EXCEPTION: main
    Process: com.keerthan.locationalarm2, PID: 27176
    android.view.InflateException: Binary XML file line #34: Error inflating class fragment

Caused by: java.lang.IllegalArgumentException: Binary XML file line #34: Duplicate id 0x7f0d006b, tag null, or parent id 0xffffffff with another fragment for com.google.android.gms.maps.SupportMapFragment

**Comment by Srinivas-R** [comment]
Check this:

http://stackoverflow.com/questions/14928833/android-app-error-duplicate-id-0x7f04000f-tag-null-or-parent-id-0x0-with-ano

**Comment by keerthanss** [comment]
didn't work :/

**Comment by keerthanss** [comment]
In fact, now it crashes upon opening the third tab itself. lol

**Comment by keerthanss** [comment]
added this line and it seems to help, maybe not as efficiently though. - viewPager.setOffscreenPageLimit(4);
Now I can smoothly swipe across all tabs

however, now I get a new error :P It isn't able to destroy the activity properly.
Reason being, it is calling the onSaveInstanceState instead

04 14:44:57.769  26295-26295/com.keerthan.locationalarm2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.keerthan.locationalarm2, PID: 26295
    java.lang.RuntimeException: Unable to destroy activity {com.keerthan.locationalarm2/com.keerthan.locationalarm2.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

**Comment by Srinivas-R** [comment]
And how should we solve the new error? :P
And what does this do: viewPager.setOffscreenPageLimit(4);

**Comment by keerthanss** [comment]
It saves the state of each page, instead of pausing it or deleting it

**Comment by keerthanss** [comment]
Anyway, with now only two tabs, and the settings button in menu, the app works fine. No errors due to tabs anymore :P
